ウェブサイトの追加
approvers/github-secretary pull request #15
Opened 2020-09-27 05:44 UTC by MikuroXina

OAuth 認証機能の追加などのためにウェブサーバー機能を追加します

2020-09-28 06:27 UTC, siketyan requested changes

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/branch.ts
> +export interface PartialBranch {
```suggestion
export type PartialBranch = Pick<Branch, "name">;
```

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/issue.ts
> +export interface PartialIssue {
```suggestion
export type PartialIssue = Pick<Issue, "html_url"> & Pick<Issue, "name"> & Pick<Issue, "number">;
```

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/pr.ts
> +export interface PartialPullRequest {
```suggestion
export type PartialPullRequest = Pick<PullRequest, "html_url"> & Pick<PullRequest, "name"> & Pick<PullRequest, "number">;
```

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/pr.ts
> +  user: {
そういえば User / Author あたりも型で出しておきたくないですか（Issue と共有できるため）

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/pr.ts
> +    .map((processor) => processor(query))
```suggestion
    .map(processor)
```

2020-09-28 06:27 UTC, siketyan commented on src/bot/op/bring/repo.ts
> +    .map((processor) => processor(query))
```suggestion
    .map(processor)
```

2020-09-28 06:27 UTC, siketyan commented on src/bot/skin/github-api.ts
> +        Authorization: `Basic ${Buffer.from(`${userName}:${token}`).toString(
おんなじ構築を複数箇所でしてるので外に切り出しておきたい

2020-09-28 06:27 UTC, siketyan commented on src/bot/skin/plain-db.ts
> +    console.log("Database file doesn't exist, so start to make a new one.");
本当にファイルが存在しないことによるエラーなのか確認しておきたい

2020-09-28 06:27 UTC, siketyan commented on src/web/pages/callback.tsx
> +const callback: NextPage = () => <h1>Hello from callback!</h1>;
結局 Web からの通知登録はまだ未実装？

2020-09-28 06:28 UTC, siketyan commented
スマホでレビューしたので複数行指定ができてません， Suggested Changes をそのまま Commit しないでください🙇

2020-09-28 06:29 UTC, shun-shobon requested changes
表面的なことはレビューできますが中身の内容は流石に多すぎて無理です……

2020-09-28 06:29 UTC, shun-shobon commented on src/web/tsconfig.json
> +}
行末の改行がありません。

2020-09-28 06:29 UTC, shun-shobon commented on tsconfig.json
>      ],
`target`に指定されたものが暗黙的に`lib`に設定されるのでこれは必要ないと思います。

2020-09-28 06:29 UTC, shun-shobon commented on tsconfig.json
> +}
行末の改行がありません。

2020-09-28 07:10 UTC, MikuroXina commented on src/web/pages/callback.tsx
> +const callback: NextPage = () => <h1>Hello from callback!</h1>;
そうです。通知登録を含めると大きすぎたので、ウェブサイトの追加だけです

2020-09-28 07:11 UTC, MikuroXina commented on docker/web.Dockerfile
> +  && adduser -u 1993 -S web -G web
Docker の公式サンプルか何かのコピペなのでよくわからないです

2020-09-28 07:14 UTC, siketyan commented on docker/web.Dockerfile
> +  && adduser -u 1993 -S web -G web
特に意味のあるマジックナンバーではなさそう．なので Web と Bot で分けるだけしたほうがいいとおもいます

2020-09-28 07:14 UTC, MikuroXina commented on src/bot/op/bring/pr.ts
> +  user: {
特にユースケース上の関連がないので、そこはどちらかが変化する可能性があって共通化したくないです

2020-09-28 07:16 UTC, MikuroXina commented on src/bot/op/bring/repo.ts
> +    .map((processor) => processor(query))
そのような書き換えはできないと思います (他も同様)

2020-09-28 07:18 UTC, MikuroXina commented on src/bot/skin/plain-db.ts
> +    console.log("Database file doesn't exist, so start to make a new one.");
`r+` でエラーが起こるのはファイルが存在しない時だけです

2020-09-28 10:07 UTC, MikuroXina commented on docker/web.Dockerfile
> +  && adduser -u 1993 -S web -G web
e37504c で修正

2020-09-28 10:44 UTC, MikuroXina commented on src/bot/op/bring/branch.ts
> +export interface PartialBranch {
3cf89a2 で対応

2020-09-28 10:44 UTC, MikuroXina commented on src/bot/op/bring/issue.ts
> +export interface PartialIssue {
3cf89a2 で対応

2020-09-28 10:44 UTC, MikuroXina commented on src/bot/op/bring/pr.ts
> +export interface PartialPullRequest {
3cf89a2 で対応

2020-09-28 10:50 UTC, MikuroXina commented on src/bot/skin/github-api.ts
> +        Authorization: `Basic ${Buffer.from(`${userName}:${token}`).toString(
a70adb4 で対応

2020-09-28 10:51 UTC, siketyan commented on src/bot/op/bring/pr.ts
> +  user: {
たしかに．

2020-09-28 10:53 UTC, siketyan commented on src/bot/op/bring/repo.ts
> +    .map((processor) => processor(query))
ですね……

2020-09-28 10:54 UTC, siketyan commented on src/bot/skin/plain-db.ts
> +    console.log("Database file doesn't exist, so start to make a new one.");
あんまりないケースですがディスク不良とかの IO エラーもありえませんか……？

2020-09-28 10:58 UTC, MikuroXina commented on package.json
> +    "lint": "eslint --ext .ts,.tsx --ignore-pattern *.d.ts --ignore-path .gitignore ./src/",
c6bd5e1 で対応

2020-09-28 11:15 UTC, MikuroXina commented on .eslintrc.json
> +    "ecmaVersion": 12,
628a37c で対応

2020-09-28 11:16 UTC, MikuroXina commented on .eslintrc.json
> +    "plugin:prettier/recommended"
628a37c で対応

2020-09-28 11:16 UTC, MikuroXina commented on .eslintrc.json
>  }
628a37c で対応

2020-09-28 11:18 UTC, MikuroXina commented on tsconfig.json
> +}
34b325c で対応

2020-09-28 11:18 UTC, MikuroXina commented on src/web/tsconfig.json
> +}
34b325c で対応

2020-09-28 11:18 UTC, MikuroXina commented on .prettierrc.json
> +}
34b325c で対応

2020-09-28 11:20 UTC, MikuroXina commented on tsconfig.json
>      ],
95a09a6 で対応

2020-09-28 11:34 UTC, MikuroXina commented on src/bot/skin/plain-db.ts
> +    console.log("Database file doesn't exist, so start to make a new one.");
25d78e4 で対応

2020-09-28 12:12 UTC, shun-shobon approved these changes

2020-09-28 12:12 UTC, MikuroXina commented on docker/web.Dockerfile
> +ENTRYPOINT [ "npx", "next", "start" ]
特に `npx` を使っても毎回インストール処理は走らないように思うのですが, 詳しく教えてほしいです

2020-09-30 03:26 UTC, kawaemon approved these changes

2020-09-30 03:26 UTC, kawaemon commented on src/bot/skin/toml-loader.ts
>      const jsonStr = buf.toString();
細かいけど。。。
```suggestion
    const tomlStr = buf.toString();
```

2020-09-30 05:16 UTC, siketyan commented on docker/web.Dockerfile
> +ENTRYPOINT [ "npx", "next", "start" ]
ごめんなさい依存にあればダウンロードは走らなさそう．ただ npm scripts でいい気もする

2020-09-30 05:21 UTC, MikuroXina commented on docker/web.Dockerfile
> +ENTRYPOINT [ "npx", "next", "start" ]
現状の npm scripts が `.src/web` に対して直接実行することを想定しているので, このままにします

2020-09-30 05:26 UTC, siketyan approved these changes

2020-09-30 05:28 UTC, merged